### ISSUE TITLE
Data race when trying to connect to replica sets

### ISSUE THREAD

**Issue by yavuzyurtbegendi** [globalsign/mgo#227] opened 2018-07-30 09:20 UTC
Connecting to my mongodb replicas like this,
```
session, err := mgo.Dial("10.118.1.100:27017,10.118.1.100:27018,10.118.1.100:27019")
```
after a node is down, I am getting this log,
```
WARNING: DATA RACE
Read at 0x00c42041e1e0 by main goroutine:
  /***/github.com/globalsign/mgo.(*Session).acquireSocket()
      /***/github.com/globalsign/mgo/session.go:5110 +0x6e9
  /***/github.com/globalsign/mgo.(*Collection).writeOp()
      /***/github.com/globalsign/mgo/session.go:5312 +0xef
  /***/github.com/globalsign/mgo.(*Collection).Insert()
      /***/github.com/globalsign/mgo/session.go:3001 +0x10a
  main.main()
      /***/main.go:93 +0x403

Previous write at 0x00c42041e1e0 by goroutine 23:
  /***/github.com/globalsign/mgo.(*mongoSocket).kill()
      /***/github.com/globalsign/mgo/socket.go:368 +0x253
  /***/github.com/globalsign/mgo.(*mongoSocket).readLoop()
      /***/github.com/globalsign/mgo/socket.go:602 +0x1166

Goroutine 23 (finished) created at:
  /***/github.com/globalsign/mgo.newSocket()
      /***/github.com/globalsign/mgo/socket.go:200 +0x377
  /***/github.com/globalsign/mgo.(*mongoServer).Connect()
      /***/github.com/globalsign/mgo/server.go:259 +0x5c6
  /***/github.com/globalsign/mgo.(*mongoServer).acquireSocketInternal()
      /***/github.com/globalsign/mgo/server.go:207 +0x364
  /***/github.com/globalsign/mgo.(*mongoServer).AcquireSocket()
      /***/github.com/globalsign/mgo/server.go:125 +0x4b
  /***/github.com/globalsign/mgo.(*mongoCluster).syncServer()
      /***/github.com/globalsign/mgo/cluster.go:209 +0x2b9
  /***/github.com/globalsign/mgo.(*mongoCluster).syncServersIteration.func1.1()
      /***/github.com/globalsign/mgo/cluster.go:541 +0x1fa
```

Than, it stops connecting to any available mongodb instance,
```
no reachable servers
no reachable servers
no reachable servers
no reachable servers
no reachable servers
```

**Comment by tadukurow** [comment] 2018-07-30 21:40
Hi @yavuzyurtbegendi, thanks for reporting this.
It looks like this is a duplicate of #223 as in both issues the data race occurs when reading socket.dead outside of the socket lock. 

I'm closing this in favour of #223. Please check the discussion there for further information.

**Closed by tadukurow** 2018-07-30 21:40 UTC
Labels: duplicate

**Comment by tadukurow** [comment] 2018-07-30 22:45
Sorry, after further investigation it turns out #223 was a duplicate of #135.
So please check #135 for futher discussion on this issue.
