### ISSUE TITLE
Collection.EnsureIndex creates a undesired index name

### ISSUE THREAD

**Issue by gnixuygnahz** [globalsign/mgo#340] opened 2019-03-26 16:37 UTC
### What version of MongoDB are you using (`mongod --version`)?
```
github.com/globalsign/mgo v0.0.0-20181015135952-eeefdecb41b8
```

### What version of Go are you using (`go version`)?
```
go version go1.11.4 windows/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
windows10   ,  no
```

### What did you do?
when i run this:
```
	index := mgo.Index{
		Name:       "objectId_1",
		Key:        ["objectId"],
		Unique:     true,
		Background: true,
		Sparse:     sparse,
	}
	err := db.C(tb).EnsureIndex(index)
```
it created a index naming "uqx_name"

### Can you reproduce the issue on the latest `development` branch?
yes

**Comment by domodwyer** [comment] 2019-04-01 13:41
Hi @gnixuygnahz 

I'm going to close this as I'm unable to reproduce - happy to reopen if you have a runnable example though!

Dom

**Closed as completed by domodwyer** 2019-04-01 13:41 UTC
