### ISSUE TITLE
Best practice

### ISSUE THREAD

**Issue by pjebs** [globalsign/mgo#76] opened 2018-01-13 10:46 UTC
I notice there is a `session, err := mgo.Dial(MONGODB_DIAL_URL)` function and also `Clone` and `Copy`.

If we are using MongoDB for a web app backend, I'm wondering what the best practice is out of these options.

1) Call Dial when we need to access database and close as soon as possible (usually with defer within same function).

2) Call Dial at start of request and close at end of request cycle after servicing request.
- Obviously if we must do multiple queries per request, we use the same reference to session _during_
  that request.

3) Call Dial external to request cycle (i.e. when app starts up), store the reference in a global variable and keep using it independent of request and usually never close connection and just let the library do connection pooling.

(Obviously For option 2, an improvement is to dial lazily but that's obvious to readers).
Assuming that we may need to do multiple database queries per request, how exactly do we use `clone` and/or `copy`?

**Comment by pjebs** [comment] 2018-01-13 10:46
Can you please provide guidance (since you are the only authority in the matter) on how and when to use `clone` and `copy`.

**Comment by pjebs** [comment] 2018-01-13 10:47
See also:
https://groups.google.com/forum/#!topic/mgo-users/pk9IsU2bb8o
http://stackoverflow.com/questions/33275357/should-i-copy-session-for-each-operation-in-mgo

**Comment by pjebs** [comment] 2018-01-13 10:49
This is a copy of: https://github.com/go-mgo/mgo/issues/287 which the origianal author did not answer. It would be great if a higher power answered it because I noticed there are 100's of people asking the same question on forums and many are linking to my original issue.

Thank you for your time.

**Comment by pjebs** [comment] 2018-01-13 10:50
Does this package do connection pooling similar to `database/sql`?

**Comment by domodwyer** [comment] 2018-01-14 14:18
Hi @pjebs 

You're not the first to ask this! I'd suggest using `session.Copy()` to automatically open a new socket to the Mongo server if needed, or reuse an existing socket if available. This means your application will "warm up" to the number of connections needed for the load in the first few minutes of operation.

You could use `Clone()` which uses the same underlying socket, but past a certain level of concurrency your application will be bound by contention caused by sharing the single socket. Depending on your workload this might not be an issue, but it's likely going to be a nasty surprise!

Calling Dial each time involves opening a connection, performing any authentication (not cheap) and then closing it when you're done, having to do it all again for the next request - this is a lot of round trips and very expensive for both the client and server - **you should avoid this method**.

I've [added an example](https://github.com/globalsign/mgo/pull/78) to the documentation - this should make it into the master branch / godoc.org soon.

I hope this helps, does it answer all your questions?

Dom

**Comment by pjebs** [comment] 2018-01-14 20:18
thank you.

**Closed** 2018-01-15 21:40 UTC
Labels: question
