### ISSUE TITLE
Data Race When Server Has Gone

### ISSUE THREAD

**Issue by exordium-frozen** [globalsign/mgo#223] opened 2018-07-21 01:15 UTC
Hi there!

Got race condition:
```
==================
WARNING: DATA RACE
Read at 0x00c4200bbe00 by goroutine 12:
  .../vendor/github.com/globalsign/mgo.(*Session).acquireSocket()
      .../vendor/github.com/globalsign/mgo/session.go:5110 +0x6e9
  .../vendor/github.com/globalsign/mgo.(*Database).Run()
      .../vendor/github.com/globalsign/mgo/session.go:992 +0x5d
  .../vendor/github.com/globalsign/mgo.(*Session).Run()
      .../vendor/github.com/globalsign/mgo/session.go:2489 +0xb9
  .../vendor/github.com/globalsign/mgo.(*Session).Ping()
      .../vendor/github.com/globalsign/mgo/session.go:2525 +0x5c

Previous write at 0x00c4200bbe00 by goroutine 63:
  .../vendor/github.com/globalsign/mgo.(*mongoSocket).kill()
      .../vendor/github.com/globalsign/mgo/socket.go:368 +0x253
  .../vendor/github.com/globalsign/mgo.(*mongoSocket).readLoop()
     .../vendor/github.com/globalsign/mgo/socket.go:602 +0x1166
```

Commit `113d396`.
Steps to reproduce:
1. Connect using the following settings:
```golang
ses, err := mgo.DialWithTimeout(url, timeout)
if err != nil {
	return nil, errors.Wrapf(err, "mgo.DialWithTimeout: %s, %v", url, timeout)
}

ses.SetMode(mgo.Monotonic, true)
```
2. Shutdown the server
3. Try to perform a call:
```golang
ses.Ping()
```
4. Get a race.

This race is being reproduced in 100% cases.

Running on a system:
- macos Sierra 10.12.6
- `go version go1.10.2 darwin/amd64`
- mgo commit `113d396`

**Comment by tadukurow** [comment] 2018-07-30 21:45
I had a quick look and the race happens when acquiring a new socket, it is checked for liveness outside the socket lock. It looks like we should be able to get a fix out for this shortly.

**Comment by tadukurow** [comment] 2018-07-30 22:43
After further investigation, this is a duplicate of #135.
I'm closing this issue in favour of continuing the discussion on #135

**Closed by tadukurow** 2018-07-30 22:43 UTC
Labels: bug
